### ISSUE TITLE
Microsoft Eva And Other Cortana-based voices do not merge.

### ISSUE THREAD

**Issue by Windows-Electronic101** [Mahmood-Taghavi/SAPI_Unifier#2]
Hi there. I just wanted to say thank you for providing us with this great tool to bring OneCore and Speech Platform voices over to SAPI5. However, I have noticed something troubling. Windows 10 has hidden voices which are locked and restricted by Cortana by default, but they can be unlocked with registry keys. Some examples are Eva Mobile - English (United States), Sarah Mobile - English (United Kingdom), Matilda Mobile - English (Australia), Koyal Mobile - English (India), and Eva Mobile - English (Canada). There may also be other hidden voices in other languages used exclusively by Cortana by default that can be unlocked through the power of the registry. I noticed that your program does not copy these Cortana voices when searching for paths for the registry. Windows version is Windows 10 21H1 x64 (Build 19043.1083) however these unlocked voices have been a thing since the first initial release of Windows 10 made back in 2015. HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppContainer\Storage\microsoft.windows.cortana_cw5n1h2txyewy\SOFTWARE\Microsoft\Speech_OneCore\Isolated\jWXZvMzcRxToSdOzNgXV_L3ZSrLDNbZuY5NZNWCCUd8\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens is the registry path where these voices are stored.

**Comment by Mahmood-Taghavi** [comment]
Hi, 
Thanks for your comment.
Microsoft did not let users employ Cortana voices in third-party apps and I do not like to broke their rule.
Thanks again for your comment.
Regards
Mahmood
