### ISSUE TITLE
"Desktop" voices are being cloned, why?

### ISSUE THREAD

**Issue by Windows-Electronic101** [Mahmood-Taghavi/SAPI_Unifier#4]
Hello again.
As I was noticing the other issue, I had come across that the app is not checking for clones of already existing voices on SAPI5, for example Microsoft David and Microsoft Zira have been copied to the registry twice as a result of their mobile counterparts existing. However, the voices sound exactly the same. Same pitch controls, same speed controls, same tone of voice. In other words,there should be some sort of filter to detect when a mobile voice has a desktop counterpart and does not clone that voice.

**Comment by Mahmood-Taghavi** [comment]
Hi,
Thanks for your comment.
I did not intend to filter voices out by similarity in their name. 
So users have the authority to use all voices.
Thanks again for your comment.
